### ISSUE TITLE
Initialization authorization link doesn't show up/unclickable

### ISSUE THREAD

**Issue by sglkc** [lyricstify/lyricstify#2]
I found a quite specific issue while trying to initialize lyricstify.

I'm using Xfce4 Terminal with [Starship](https://starship.rs/) and when I tried to initialize, the link cannot be clicked and there's nothing beside it. So I tracked the code to find that [/src/initialize/initialize.command.ts:51](https://github.com/lyricstify/lyricstify/blob/main/src/initialize/initialize.command.ts#L51) uses [terminal-link](https://www.npmjs.com/package/terminal-link) to print the auth link.

![Screenshot](https://user-images.githubusercontent.com/31957516/230090112-089a9385-db4c-48aa-a3a9-cb845a8364e4.png)

While this might be because terminal-link doesn't support Xfce Terminal, I think it's still worth mentioning this just in case.

**I solved the issue by using another terminal.** 

You're free to close this issue. This is a great app nonetheless!

**Comment by yusuftaufiq** [comment]
Thanks for your report! I decided to replace all hyperlinks by displaying the URL directly, as this problem will likely occur in other terminal emulators too.

**Comment by sglkc** [comment]
Sure, if it means just to remove terminal-link package.

**Comment by yusuftaufiq** [comment]
That's good, I'll assign this issue to you. But there's no pressure though, you can open a new PR when you have time to do it because I don't think this issue is a crucial priority.
