### ISSUE TITLE
Many songs that not showing lyrics.

### ISSUE THREAD

**Issue by catfoofat** [lyricstify/lyricstify#252]
I'm someone who uses your software (Lyricstify) to sync lyrics with Spotify and for translation. 
However, a few days ago, I noticed that many songs that I listen to are not showing anymore just blank like it can't retrieve lyrics. Some are showing the same.
No matter what commands or flags I try to use, 
I wonder if there is a problem with the API that calls for lyrics or not, 
and how I can fix it. 
I even tried running it with the source code, but I still have the same issue.
I'm not sure where should I tell you about is issue. So, I post it here.

Some of tested songs. There are many songs that I try but it's not showing.

Show lyric.
- Carelress Whisper - George Michael https://open.spotify.com/track/4jDmJ51x1o9NZB5Nxxc7gY?si=4561ef9942c04a6b
- Stayin' Alive - Bee Gees - https://open.spotify.com/track/4UDmDIqJIbrW0hMBQMFOsM?si=76a9c7e005334d3a

Not Showing (I'm sure it's showing before)
- Because of You - Kelly Clarkson https://open.spotify.com/track/0gJvqi9QyASOCtJu99tytc?si=48278f0f8c0b4a2a
- Gira Gira - Ado https://open.spotify.com/track/0vHCmjN8pepvdu41r69gcB?si=642296bfa8fd4d38

**Comment by catfoofat** [comment]
It seems like your server API is missing `spotifycookie` right now.
But I'm able to run it by running `lyricstify/api` side by side and changing main `lyricstify` to point to that local endpoint.

**Comment by quadrinex** [comment]
@catfoofat 
> It seems like your server API is missing `spotifycookie` right now. But I'm able to run it by running `lyricstify/api` side by side and changing main `lyricstify` to point to that local endpoint.

How did you made lyricstify point to that local endpoint?
