### ISSUE TITLE
this.lyrics.at is not a function

### ISSUE THREAD

**Issue by abednegosteven** [lyricstify/lyricstify#7]
So I already followed all the installation and configuration steps, but it still gave me "this.lyrics.at is not a function" error when I tried to start the app. 

![Screenshot from 2023-04-13 10-24-59](https://user-images.githubusercontent.com/65885872/231641127-e853cbae-7e6a-459d-8480-bbbdb268f8ab.png)

Some help will be really appreciated, thankyou!

**Comment by yusuftaufiq** [comment]
What version of Node.js are you using? It looks like you are using an old version of Node.js (probably < 16). Then, I'd like to suggest you upgrade to the latest LTS version or higher ([18](https://nodejs.org/en/download) or [19](https://nodejs.org/en/download/current)).

Let me know if this solution still doesn't work.

**Comment by abednegosteven** [comment]
I've just updated my node version as you suggest, and now the app works well. 
Thank you so much for the helps!
